[shell]
date_format = "%A, %F"
font_family = "Adwaita Sans"
polkit_agent = true

[theme]
builtin = "Rosé Pine"
community_palette = "Rose Pine Moon"
mode = "dark"
source = "community"

[widget.control-center]
custom_image = "/usr/share/noctalia/assets/images/etheria.png"
scale = 1.6000000000000001
